// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Article struct {
	ID        string
	Title     string
	CreatedAt int64
	AccountID string
}

type ArticleContent struct {
	ID        string
	CreatedAt int64
	ArticleID string
	Content   string
}

type Comment struct {
	ID        string
	CreatedAt int64
	AccountID string
	ArticleID string
}

type CommentContent struct {
	ID        string
	CreatedAt int64
	CommentID string
	Content   string
}

type UserAccount struct {
	ID          string
	DisplayName string
	Password    string
	CreatedAt   int64
	UpdatedAt   int64
}
