// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Article struct {
	ID        string
	CreatedAt int32
	AccountID string
}

type ArticleContent struct {
	ID        string
	CreatedAt int32
	ArticleID string
	Title     string
	Content   string
}

type Comment struct {
	ID        string
	CreatedAt int32
	AccountID string
	ArticleID string
}

type CommentContent struct {
	ID        string
	CreatedAt int32
	CommentID string
	Content   string
}

type UserAccount struct {
	ID          string
	DisplayName string
	Password    string
	CreatedAt   int32
	UpdatedAt   int32
}
