// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Article struct {
	ID        string
	Title     string
	Content   string
	CreatedAt int64
	AccountID string
}

type UserAccount struct {
	ID          string
	DisplayName string
	Password    string
	CreatedAt   int64
	UpdatedAt   int64
}
